# Change these first
owner: gnosischain
repo: gnosischain-uptime
sites:
  - name: "RPC"
    method: POST
    url: https://rpc.gnosischain.com/
    headers: ["Content-Type: application/json"]
    body: |
      {
        "method": "eth_blockNumber",
        "params":[],
        "id":1,
        "jsonrpc":"2.0"
      }
  - name: "GatewayFM Public RPC"
    method: POST
    url: https://rpc.gnosis.gateway.fm/
    headers: ["Content-Type: application/json"]
    body: |
      {
        "method": "eth_blockNumber",
        "params":[],
        "id":1,
        "jsonrpc":"2.0"
      } 
  - name: "Beacon RPC"
    url: https://rpc-gbc.gnosischain.com/eth/v1/beacon/headers
  - name: "Gnosisscan"
    url: https://gnosisscan.io/
  - name: "Blockscout Explorer"
    url: https://blockscout.com/xdai/mainnet
  - name: "Beacon Explorer"
    url: https://gnosischa.in/api/healthz
  - name: "Faucet"
    url: https://api.faucet.gnosischain.com/api/v1/status
    headers: ["User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)"]
  - name: "Ethstats"
    url: https://ethstats.gnosischain.com/
  - name: "Bridge Explorer"
    url: https://bridge-explorer.gnosischain.com/
  - name: "xDaiBridge"
    url: https://bridge.gnosischain.com/
  - name: "Beacon Checkpoint Sync"
    url: https://checkpoint.gnosischain.com/
status-website:
  name: GnosisChain
  introTitle: "**GnosisChain** the Community-Run Chain"
  introMessage: Check the availability for GnosisChain services
  cname: status.gnosischain.com
  theme: light



